### PR TITLE
Remove gpredict.pot and add it to the gitignore

### PR DESCRIPTION
**Pull request by jasonuher**
This was my solution to issue #56 

I've done several "build from clean slate" and had no issues (though, I also only use en-us...)

### CODE REVIEW

**Comment by csete** [comment]
We have to make sure this doesn't break the [translation work on the Launchpad](https://translations.launchpad.net/gpredict).

**Comment by jasonuher** [comment]
I agree, but I am only able to test the english us build at this point (I don't speak any other languanges).

Based on my (admittedly, limited) understanding of gettext the .pot file is supposed to be automatically generated at build time using the _("...") macros that are surrounding all translatable strings.  I think the idea is that you do not have to manually specify every string to be generated.  

I tested this idea by running automake against branches both with and without the *.pot file.  In both cases the file was generated and placed in the correct location.

At this point we would need someone to test this by compiling with a different language and verifying that the strings showed up properly.

**Comment by csete** [comment]
@jasonuher I wasn't referring to translations but the translation work itself done by the Ubuntu community on the [Launchpad](https://translations.launchpad.net/gpredict). I just don't remember what that system requires as input.

**Comment by csete** [comment]
Okay, let's try this.

**Pull request merged**
