### PR TITLE
handle az rotation stops in non-standard positions

### PR DESCRIPTION
**Pull request by somewhere-or-other**
This code should handle the azimuth rotation stops in non-default positions.  Feel free to change the look of the GUI components, if needed, though I hope they're fairly intuitive. - Lloyd

### CODE REVIEW

**Comment by csete** [comment]
Hi Lloyd,

I took a quick look at it and it looks good. However, I'm not sure I can see the purpose with "azstopposdefault". It adds a lot of code but I don't see it used anywhere in gtk-rot-ctrl. Can you please clarify?

**Comment by somewhere-or-other** [comment]
Sure.  I wondered if that might not be entirely clear.  I should have probably put in better comments, etc.  I can do that if you want.

In short, as much as possible, I wanted to maintain the current behavior.  Specifically, if the user has *not* specified a custom position, I want to keep the position set to the default for the az type, even when they change types.  However, if the user has specified a custom position, I wanted to always maintain that value, despite any az type changes.

So, I needed a way to figure out whether or not the user was intending to have the default value.  In _most_ scenarios I could guess by comparing azstoppos with minaz.  But there was at least one scenario I could think of, in which that could get us into trouble.

Here's the scenario: Someone is using a (-180->0->180) az rotor, with a custom stop position at 0 (north).  If they accidentally switch types to a (0->180->360) rotor, that custom stop would be maintained at 0, since it's a non-default value for a (-180->0->180) rotor.  They then realize their mistake and switch back from (0->180->360), to (-180->0->180) type.  The trouble is that their custom stop position of 0, now lines up with the default position of the (0->180->260) type, so if we just guess default vs non-default state, based on azstoppos==minaz, it would assume that they intended the default, and switch them to the new type's default of -180.  In short, even though the type is the same as they started out with (-180->0->180), they've gone from a custom stop position of 0 (north), to a default stop position of -180 (south).

By having an checkbox for default vs non-default, we let the user explicitly define which behavior they want, in a fairly intuitive way.  Since the checkbox is checked (meaning use the default value), by default, anyone with existing rotator configs, or new rotator configs, should get the same behavior as they currently have.

Is that clear?  I can try to explain again if needed.  And if you would like, I'll put in better code comments, and maybe some tooltips, to make it clearer, for both developers and users.

**Comment by csete** [comment]
Ok, thanks for the clarification.

I think I would prefer that we only have the end stop angle and don't care whether it is default or not. Whenever the user changes the AZ type, the end stop angle is reset to the default value for that type. The user can then change it to a non-default value if necessary. It may be inconvenient in some cases but at the end, this configuration is created once and then probably never touched again.

**Comment by somewhere-or-other** [comment]
Okay.  I'll see if I can strip it back down to just the one value.  Might take me a few more days.  I'll post here when it's ready.

**Comment by csete** [comment]
Sounds good, and sorry to be such a pain :)

**Comment by somewhere-or-other** [comment]
A pain?  It's much more of your project than mine.  I was trying to anticipate a potential problem, but if you don't think it's worth the code complexity, I'll take it back out.

If anything, I'm annoyed with myself. Without the complexity of the extra component, it would have been ready at least a week ago.

Oh well.

**Comment by somewhere-or-other** [comment]
Alex,

Does this look any better?  I mostly just reverted to an earlier revision from my dev branch, and cleaned up some of the UI elements.

Lloyd

**Comment by csete** [comment]
Hi Lloyd,

It's very good, thanks. I have merged your patch manually because I wanted to squash your commits into one. So, you can't see it here, but if you look at the commit log you will see a commit  made by you.

Alex

**Pull request closed without merging**
