### PR TITLE
satnogsDB integration

### PR DESCRIPTION
**Pull request by barisdinc**
This is the required json parsing and SatnogsDB download parts...

### CODE REVIEW

**Comment by csete** [comment]
I am bit confused here... Did you use the satnogsdb branch as starting point?

Please start with the satnogsdb branch as starting point as it already contains your previous changes, add your new changes and submit the pull request with respect to my satnogsdb branch.

**Comment by barisdinc** [comment]
that was what I intended to do.. but I was not able to see that brranch in
my fork..

Maybe I should re-fork your repository..

My screenshot is in attachment..

Let me give it a try again



baris
..

**Comment by barisdinc** [comment]
I found the reason... Thats because you added the new branch after I forked it... So I cannot see the new branch, even after update...

Now I have access to satnogs branch in my local fork/copy...

I will try to push changes into this branch..

thanks
baris

**Comment by barisdinc** [comment]
I re-forked the repository and prepared a new pull request.. I am closing this request...

**Comment by csete** [comment]
Thanks for lookiing into it :-)

**Pull request closed without merging**
