### PR TITLE
Crash fix

### PR DESCRIPTION
**Pull request by drid**
Fixes crash but we need some message/popup to inform user that it failed.

### CODE REVIEW

**Comment by csete** [comment]
It still crashes.

**Comment by drid** [comment]
Cannot reproduce on my system but changed 0 checking to NULL and added some logging.
If it still crashes set a breakpoint just before the lines i added if possible.

**Comment by csete** [comment]
Your fix is the right thing to do but it doesn't fix the error I reported.

Please squash your commits; there is no reason to have two commits, where the second commit fixes the first one.

**Comment by csete** [comment]
Thanks.

**Comment by csete** [comment]
FYI, this was the error causing the crash for me: 407865c0d9f4e49533ac45242e816acf4fa97f6c

**Pull request merged**
