### PR TITLE
Add flatpak-builder specfile

### PR DESCRIPTION
**Pull request by sielicki**
This makes it simple to build for flatpak with flatpak-builder. There is not
yet any application in place to add this to flathub.

Signed-off-by: Nicholas <sielicki@yandex.com>

### CODE REVIEW

**Comment by sielicki** [comment]
Please let me know if you have any questions about building using this file. The gist of it is like this

1. distro-specific: install flatpak and flatpak-builder

2. grab the gnome runtime and sdk (see here: https://flatpak.org/runtimes )

`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

`flatpak install flatpak org.gnome.Platform//3.26 org.gnome.Sdk//3.26`

3. build gpredict

`flatpak-builder --repo=localrepo gpredict net.oz9aec.Gpredict.json`

4. Make flatpak aware of your new local repo

`flatpak --user remote-add --no-gpg-verify --if-not-exists localrepo localrepo`

5. Install the gpredict flatpak app from your new local repo

`flatpak --user install privrepo net.oz9aec.Gpredict`

6. Run it

`flatpak run net.oz9aec.Gpredict`

**Comment by csete** [comment]
Thanks, but I have no prior knowledge about flatpak and I don't even understand what the above steps do. Does it create some application bundle that I can distribute to users?

I'm afraid I will have to read up on this technology to understand what it is and how it works before I can adopt it.

**Comment by csete** [comment]
Ok, but all I meant was that I need some time to understand what this is, and right now it's a bad time.

**Comment by sielicki** [comment]
Hey no worries! I sprung this on you with very little explanation, and I'm sorry about that. 

Flatpak is similar to some other new distribution methods that you might have heard of like Snaps and AppImages. I'm certainly not qualified to give a big overview of all 3, but Flatpak targets graphical/desktop applications primarily, and my read (as of right now) is that flatpak has the most momentum and is the best engineered.

Bottom line is that there's absolutely no reason that this flatpak-builder file has to live in this repository. I'm going to clean this up and make it suitable for addition to flathub. This will make it easy for anyone to install gpredict from their graphical software center, at least for KDE and Gnome users, (and provided that they have the flathub repository on their machine.) I'll track progress here: https://github.com/csete/gpredict/issues/119

Once that's prepared, I'll reach out so you can get access to push updates to flathub (if you're interested). In practice, this is nothing more than bumping versions when you push a new release.

Again, sorry for the poor communication, and thanks for the work you do on gpredict.

**Comment by csete** [comment]
Hi @sielicki 

Thank you for the update and clarification. I am definitely interested in making distribution and integration as good as possible. I will keep an eye on the progress.

**Pull request closed without merging**
