### PR TITLE
New TRSP files

### PR DESCRIPTION
**Pull request by prstoetzer**
Created TRSP files for amateur satellites EO-88, LO-90, CAS-4A, and CAS-4B.

### CODE REVIEW

**Comment by csete** [comment]
Thanks for the patch, but we no longer distribute the trsp files with gpredict. You can now import transponder data from https://db.satnogs.org/ and so this is where new data should be added.

**Comment by csete** [comment]
Forgot to mention, you can import data through the menu: Edit -> Update transponder data

**Comment by prstoetzer** [comment]
Thanks. I did not realize SatNogs was the source for that new feature. Just submitted several suggestions to fix some of the data that gets imported (many inverting linear transponders were not marked as such).

**Comment by csete** [comment]
Hehe, yes, gpredict is a bit "work in progress" right now.

Thanks for submitting the changes to Satnogs DB. I have just approved them so they should become available in both gpredict and the Satnogs scheduling shortly.

**Pull request closed without merging**
