### PR TITLE
Add Iridium NEXT

### PR DESCRIPTION
**Pull request by schneider42**
Adds the category and fetches the TLEs from celestrak.

I'm not sure if it already makes sense to add them to `satellites.dat`

### CODE REVIEW

**Comment by csete** [comment]
Thanks for the patch, however, I am deliberately trying to reduce the amount of data bundled with gpredict and make it easy to add new data instead, which would include new categories.

It's still a work a in progress and I have not yet decided how much to include and remove, but I do not wish to any any new non-hamradio satellites at the moment.

**Comment by schneider42** [comment]
Would it be OK to only add the TLE location in `src/sat-cfg.c`?

**Comment by csete** [comment]
> Would it be OK to only add the TLE location in src/sat-cfg.c?

Not for now, because the satellites would still be downloaded the first time the user runs an update. Note that the list in sat-cfg.c is just a predefined default and you can add more URLs to your own config through Preferences -> TLE Update.

**Comment by schneider42** [comment]
Well, not having to do that was the original goal of this PR.

Happy hacking :)

**Comment by csete** [comment]
All right, I changed my mind... for now... I may change it again later.

**Pull request merged**
