### PR TITLE
Rotctl monitor mode

### PR DESCRIPTION
**Pull request by drid**
Adds monitor mode to antenna control.
Useful for monitoring SATNOGS rotator.

### CODE REVIEW

**Comment by csete** [comment]
Thanks @drid!

I didn't have time to test it, but it sounds like this could indeed be useful. However, we should consider how to integrate it with the existing functionality and whether some interaction is required. As I understand, enabling monitor mode will overrule "Track" and manual input. Perhaps its good like this, I just need some time to consider.

**Comment by drid** [comment]
What it does is inhibit the transmission of command P (capital) that sets Az/El.
When track is enabled, Az/El will be set but not sent to rotctld.
Maybe for better UX i should disable Track button and Az/El controls when monitor is checked.

**Comment by csete** [comment]
Thanks for the update. I think it is good now; however, I made two minor changes:

1. Engage button does not disable Monitor. I think it is useful to be able to toggle Monitor even when Engage is active
2. I moved the Monitor widget down below the rotor selector to save window width, see screenshot

screenshot_906

If you agree with these changes I will merge ASAP. You don't need to update the code because I already have the above described changes locally

**Comment by drid** [comment]
I think it is ok, users should be able to deduce that since AzEl controls are disabled no commands are sent despite numbers changing when track is on.

**Pull request merged**
