### PR TITLE
Fix Window build

### PR DESCRIPTION
**Pull request by amoffet**

### CODE REVIEW

**Comment by csete** [comment]
Hi Alan,

Thanks for the fix. Could you elaborate on what it fixes? The existing build files worked fine for me last time I built windows binaries in 2019.

**Comment by amoffet** [comment]
Sure.  I followed the instructions you did - by installing MSYS and GTK+ (See https://github.com/csete/gpredict/issues/110).  My host is Windows 10.  I had to add loaders for png and jpg to support the background images and icons.  I also had to add the Adwaita icons - since the default set no longer supplies all of the used icons.  The paths in the current version of MSYS have been normalized across host types so that the correct version of utilities are invoked depending on the environment you start (32 vs 64 bit). And the distribution does not included all of the files that are present in your example build (http://files.oz9aec.net/gpredict/temp/gpredict-win32-2.1.156.zip).  I haven't figured out the localization resources yet - so far I simply included the docs.  I am not sure why these things were necessary using MSYS, from 2019 to now, but I have successfully created both 32 and 64 bit versions with the changes.  srcejon highlighted most of them in his patch, although I took a slightly different approach and came to the solution independently.

**Comment by csete** [comment]
Thanks a lot for the clarification. I will check merge it the next time I make a build for Windows in the near future. I hope you don't mind, I just prefer testing patches before merging.

**Comment by amoffet** [comment]
I don't mind at all.  I am happy that you are mindful of the quality.  If you learn anything from your build, I'd love to know about it.  Thank you for your work on gpredict and gqrx - I very much appreciate your contribution.

**Pull request merged**
